"""Initial database schema

Revision ID: 712cac0c384b
Revises: 
Create Date: 2026-01-21 11:03:18.420101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '712cac0c384b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('athletes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.String(), nullable=False),
    sa.Column('strava_athlete_id', sa.Integer(), nullable=True),
    sa.Column('strava_access_token', sa.String(), nullable=True),
    sa.Column('strava_refresh_token', sa.String(), nullable=True),
    sa.Column('strava_token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('last_strava_sync', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('strava_athlete_id')
    )
    op.create_index(op.f('ix_athletes_athlete_id'), 'athletes', ['athlete_id'], unique=True)
    op.create_table('profile_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('profile_date', sa.DateTime(), nullable=False),
    sa.Column('profile_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_snapshots_athlete_id'), 'profile_snapshots', ['athlete_id'], unique=False)
    op.create_index(op.f('ix_profile_snapshots_profile_date'), 'profile_snapshots', ['profile_date'], unique=False)
    op.create_table('training_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('methodology_id', sa.String(), nullable=False),
    sa.Column('plan_start_date', sa.DateTime(), nullable=False),
    sa.Column('plan_duration_weeks', sa.Integer(), nullable=False),
    sa.Column('fragility_score', sa.Float(), nullable=False),
    sa.Column('plan_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_plans_athlete_id'), 'training_plans', ['athlete_id'], unique=False)
    op.create_index(op.f('ix_training_plans_is_active'), 'training_plans', ['is_active'], unique=False)
    op.create_index(op.f('ix_training_plans_plan_start_date'), 'training_plans', ['plan_start_date'], unique=False)
    op.create_table('planned_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.String(), nullable=False),
    sa.Column('scheduled_date', sa.DateTime(), nullable=True),
    sa.Column('session_type', sa.String(), nullable=False),
    sa.Column('primary_zone', sa.String(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('workout_details', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['training_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_planned_sessions_plan_id'), 'planned_sessions', ['plan_id'], unique=False)
    op.create_index(op.f('ix_planned_sessions_scheduled_date'), 'planned_sessions', ['scheduled_date'], unique=False)
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('planned_session_id', sa.Integer(), nullable=True),
    sa.Column('strava_activity_id', sa.Integer(), nullable=True),
    sa.Column('activity_date', sa.DateTime(), nullable=False),
    sa.Column('activity_type', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('distance_meters', sa.Float(), nullable=True),
    sa.Column('elevation_gain_meters', sa.Float(), nullable=True),
    sa.Column('average_heartrate', sa.Float(), nullable=True),
    sa.Column('max_heartrate', sa.Float(), nullable=True),
    sa.Column('average_power', sa.Float(), nullable=True),
    sa.Column('normalized_power', sa.Float(), nullable=True),
    sa.Column('average_pace', sa.Float(), nullable=True),
    sa.Column('perceived_zone', sa.String(), nullable=True),
    sa.Column('adherence_score', sa.Float(), nullable=True),
    sa.Column('data_source', sa.String(), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], ),
    sa.ForeignKeyConstraint(['planned_session_id'], ['planned_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activities_activity_date'), 'activities', ['activity_date'], unique=False)
    op.create_index(op.f('ix_activities_athlete_id'), 'activities', ['athlete_id'], unique=False)
    op.create_index(op.f('ix_activities_planned_session_id'), 'activities', ['planned_session_id'], unique=False)
    op.create_index(op.f('ix_activities_strava_activity_id'), 'activities', ['strava_activity_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_activities_strava_activity_id'), table_name='activities')
    op.drop_index(op.f('ix_activities_planned_session_id'), table_name='activities')
    op.drop_index(op.f('ix_activities_athlete_id'), table_name='activities')
    op.drop_index(op.f('ix_activities_activity_date'), table_name='activities')
    op.drop_table('activities')
    op.drop_index(op.f('ix_planned_sessions_scheduled_date'), table_name='planned_sessions')
    op.drop_index(op.f('ix_planned_sessions_plan_id'), table_name='planned_sessions')
    op.drop_table('planned_sessions')
    op.drop_index(op.f('ix_training_plans_plan_start_date'), table_name='training_plans')
    op.drop_index(op.f('ix_training_plans_is_active'), table_name='training_plans')
    op.drop_index(op.f('ix_training_plans_athlete_id'), table_name='training_plans')
    op.drop_table('training_plans')
    op.drop_index(op.f('ix_profile_snapshots_profile_date'), table_name='profile_snapshots')
    op.drop_index(op.f('ix_profile_snapshots_athlete_id'), table_name='profile_snapshots')
    op.drop_table('profile_snapshots')
    op.drop_index(op.f('ix_athletes_athlete_id'), table_name='athletes')
    op.drop_table('athletes')
    # ### end Alembic commands ###
